platform :ios, '11.4'
use_frameworks!
inhibit_all_warnings!

target 'DeviceStateMonitor_Example' do
  pod 'DeviceStateMonitor', :path => '../'
  pod 'SwiftMessages'

  target 'DeviceStateMonitor_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.2'
    end
  end
end
